### ISSUE TITLE
can not run bin/divolte-collector ?

### ISSUE THREAD

**Issue by yspanchal** [divolte/divolte-collector#128]
Hi,

i am getting error while running bin/divolte-collector

java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

bin/divolte-collector 
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/divolte/server/Server : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by friso** [comment]
The `bin/divolte-collector` startup script performs some steps to find a suitable JDK/JRE on your system, primarily by looking at different env vars, etc. Could it be that the java executable you have on your path is different from the one you have at `$JAVA_HOME/bin/java`?

**Comment by yspanchal** [comment]
@friso thank you for the help. It was java_home issue.
