### ISSUE TITLE
Detect (and indicate) incorrect regular expression references

### ISSUE THREAD

**Issue by asnare** [divolte/divolte-collector#55]
At present we detect some problems with the mapping configuration on startup. Something that we don't verify is whether the regular expression referred to in `regex_name` and `regex_group` is defined or not.

An undefined regex currently causes the mapping failing for every request. A stack trace is logged but it doesn't clearly indicate the problem.

Instead we should:

1. Indicate the cause of the problem;
2. Preferably indicate the error on startup while loading the mapping.

An example stack trace looks like this:

```
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205) ~[na:1.8.0_20]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:459) [na:1.8.0_20]
        at java.util.concurrent.CompletableFuture$Async.run(CompletableFuture.java:428) [na:1.8.0_20]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_20]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
Caused by: java.lang.NullPointerException: null
        at io.divolte.server.RecordMapper$Context.lambda$matcher$124(RecordMapper.java:555) ~[divolte-collector-0.1-0.1-SNAPSHOT.jar:na]
        at io.divolte.server.RecordMapper$Context$$Lambda$216/427847979.apply(Unknown Source) ~[na:na]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1118) ~[na:1.8.0_20]
        at io.divolte.server.RecordMapper$Context.matcher(RecordMapper.java:555) ~[divolte-collector-0.1-0.1-SNAPSHOT.jar:na]
        at io.divolte.server.RecordMapper.lambda$null$38(RecordMapper.java:238) ~[divolte-collector-0.1-0.1-SNAPSHOT.jar:na]
        at io.divolte.server.RecordMapper$$Lambda$218/388386044.test(Unknown Source) ~[na:na]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[na:1.8.0_20]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[na:1.8.0_20]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_20]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529) ~[na:1.8.0_20]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516) ~[na:1.8.0_20]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[na:1.8.0_20]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_20]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_20]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_20]
        at io.divolte.server.RecordMapper.lambda$null$39(RecordMapper.java:239) ~[divolte-collector-0.1-0.1-SNAPSHOT.jar:na]
        at io.divolte.server.RecordMapper$$Lambda$217/400933943.apply(Unknown Source) ~[na:na]
        at java.util.Optional.flatMap(Optional.java:241) ~[na:1.8.0_20]
        at io.divolte.server.RecordMapper.lambda$regexNameFieldSupplier$40(RecordMapper.java:238) ~[divolte-collector-0.1-0.1-SNAPSHOT.jar:na]
        at io.divolte.server.RecordMapper$$Lambda$112/981487964.get(Unknown Source) ~[na:na]
        at io.divolte.server.RecordMapper.lambda$fieldSetterFromConfig$18(RecordMapper.java:128) ~[divolte-collector-0.1-0.1-SNAPSHOT.jar:na]
        at io.divolte.server.RecordMapper$$Lambda$41/2108440536.setFields(Unknown Source) ~[na:na]
        at io.divolte.server.RecordMapper.lambda$newRecordFromExchange$118(RecordMapper.java:454) ~[divolte-collector-0.1-0.1-SNAPSHOT.jar:na]
        at io.divolte.server.RecordMapper$$Lambda$147/905088515.accept(Unknown Source) ~[na:na]
        at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_20]
        at io.divolte.server.RecordMapper.newRecordFromExchange(RecordMapper.java:454) ~[divolte-collector-0.1-0.1-SNAPSHOT.jar:na]
        at io.divolte.server.IncomingRequestProcessor.process(IncomingRequestProcessor.java:72) ~[divolte-collector-0.1-0.1-SNAPSHOT.jar:na]
        at io.divolte.server.IncomingRequestProcessor.process(IncomingRequestProcessor.java:28) ~[divolte-collector-0.1-0.1-SNAPSHOT.jar:na]
        at io.divolte.server.processing.ItemProcessor.process(ItemProcessor.java:16) ~[divolte-collector-0.1-0.1-SNAPSHOT.jar:na]
        at io.divolte.server.processing.ProcessingPool.lambda$microBatchingQueueDrainerWithHeartBeat$5(ProcessingPool.java:132) ~[divolte-collector-0.1-0.1-SNAPSHOT.jar:na]
        at io.divolte.server.processing.ProcessingPool$$Lambda$10/837457281.run(Unknown Source) ~[na:na]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:454) [na:1.8.0_20]
```

**Comment by friso** [comment]
Removal of the configuration based mapping obsoletes this issue.
